In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("retail_dataset_20k.csv")
df.head()

,Order_ID,Order_Date,Product_ID,Product_Name,Category,Price,Quantity,Channel,City,Customer_ID,Stock_Available,Sales,Stock_Status
0,1,10/05/2024,1077,Shoes,Electronics,3610.49,2,Online,Delhi,6959,422,7220.98,Overstock
1,2,31/12/2024,1035,Shoes,Electronics,2164.15,2,Store,Delhi,5426,65,4328.30,Optimal
2,3,10/11/2024,1094,Sofa,Electronics,107.99,1,Store,Bangalore,5728,268,107.99,Optimal
3,4,02/05/2022,1027,Headphones,Electronics,1909.50,3,Store,Delhi,5880,178,5728.50,Optimal
4,5,12/04/2023,1097,Watch,Sports,432.02,4,Store,Bangalore,5561,212,1728.08,Optimal

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         20000 non-null  int64
 1   Order_Date       20000 non-null  object
 2   Product_ID       20000 non-null  int64
 3   Product_Name     20000 non-null  object
 4   Category         20000 non-null  object
 5   Price            20000 non-null  float64
 6   Quantity         20000 non-null  int64
 7   Channel          20000 non-null  object
 8   City             20000 non-null  object
 9   Customer_ID      20000 non-null  int64
 10  Stock_Available  20000 non-null  int64
 11  Sales            20000 non-null  float64
 12  Stock_Status     20000 non-null  object
dtypes: float64(2), int64(5), object(6)
memory usage: 2.0+ MB

In [11]:
df.describe()

,Order_ID,Product_ID,Price,Quantity,Customer_ID,Stock_Available,Sales
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,10000.500000,1049.465650,2554.060570,2.484500,5995.859250,249.780450,6346.054379
std,5773.647028,28.817338,1408.157985,1.115895,581.205845,145.016374,4769.673008
min,1.000000,1000.000000,100.040000,1.000000,5000.000000,0.000000,100.040000
25%,5000.750000,1025.000000,1348.317500,1.000000,5489.000000,124.000000,2531.942500
50%,10000.500000,1050.000000,2555.590000,2.000000,5993.000000,249.000000,4902.390000
75%,15000.250000,1074.250000,3785.065000,3.000000,6504.000000,376.000000,9294.412500
max,20000.000000,1099.000000,4999.700000,4.000000,6999.000000,499.000000,19998.800000

In [13]:
df.isnull().sum()

Order_ID           0
Order_Date         0
Product_ID         0
Product_Name       0
Category           0
Price              0
Quantity           0
Channel            0
City               0
Customer_ID        0
Stock_Available    0
Sales              0
Stock_Status       0
dtype: int64

In [15]:
df["Price"] = df["Price"].fillna(df["Price"].mean())

In [16]:
df = df.dropna()

In [17]:
df = df.drop_duplicates()

In [18]:
df["City"] = df["City"].str.strip()

In [19]:
df["City"] = df["City"].str.title()

In [22]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
print(df.columns)

Index(['order_id', 'order_date', 'product_id', 'product_name', 'category',
       'price', 'quantity', 'channel', 'city', 'customer_id',
       'stock_available', 'sales', 'stock_status'],
      dtype='object')

In [31]:
df["quantity"] = df["quantity"].astype(int)
df["price"] = df["price"].astype(float)

In [32]:
df = df[df["quantity"] > 0]

In [33]:
df = df[df["price"] > 0]

In [34]:
df["total_sales"] = df["quantity"] * df["price"]

In [36]:
print(df["price"].sort_values(ascending=False).head())

6462     4999.70
19395    4999.39
18865    4999.17
19109    4998.95
1594     4998.87
Name: price, dtype: float64

In [37]:
df.to_csv("cleaned_retail_data.csv", index=False)